Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 22, host: 7701

  config.vm.network "forwarded_port", guest: 7801, host: 8081, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7802, host: 8082, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7803, host: 8083, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7804, host: 8084, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7805, host: 8085, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7806, host: 8086, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7807, host: 8087, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7808, host: 8088, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7809, host: 8089, host_ip: "127.0.1.1"
  config.vm.network "forwarded_port", guest: 7810, host: 8090, host_ip: "127.0.1.1"

  config.vm.synced_folder "./Docker files", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant_data",
      args: "-t 'lab4'"
  end

  config.vm.provision "shell", path: "./Docker files/dock.sh"

end
