

version: "3"

services:
        
    sender:
        build: Sender/
        depends_on:
            - broker

    broker:
        build: Rabbit/
        ports:
           - 5672:5672
           - 15672:15672

    receiver:
        build: Receiver/

