apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab5
  namespace: default
spec:
  replicas: 3   # <- 3 applications
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: devops-lab5
        image: nginx:latest   # <- Nginx
        imagePullPolicy: Never
---
apiVersion: v1  # <- Liveness probe
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: nginx:latest
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1  # <- Service
kind: Service
metadata:
  name: devops-lab5-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001